'use client';
import { useEffect, useState } from 'react';
import { getSupabaseBrowserClient } from '@/lib/supabase';

type Profile = { user_id: string; full_name: string; email: string; phone: string | null; address: string | null; city: string | null; state: string | null; postal_code: string | null };
type Order = { id: string; order_number: string; order_type: string; status: string; total_amount: number | null; requested_date: string | null; created_at: string; ready_at: string | null; customer_notes: string | null; order_items: { product_name: string; quantity: number; unit_price: number }[] };
const stages = ['pending','confirmed','preparing','ready','completed'];
const label = (value: string) => value.toUpperCase();
function Progress({ status }: { status: string }) { if (status === 'cancelled') return <p className="order-cancelled">CANCELLED</p>; const current = stages.indexOf(status); return <div className="order-progress" aria-label={`Order progress: ${label(status)}`}>{stages.map((stage, index) => <div className={index <= current ? 'progress-step current' : 'progress-step'} key={stage}><span>{index + 1}</span><small>{stage === 'pending' ? 'Order Placed' : stage[0].toUpperCase() + stage.slice(1)}</small></div>)}</div>; }
function OrderCard({ order }: { order: Order }) { const active = !['completed','cancelled'].includes(order.status); return <article className={`order-card customer-order ${order.status}`}><div className="order-card-heading"><div><strong>{order.order_number}</strong><span>{label(order.order_type)}{order.order_type === 'express' && ' ORDER'}{order.order_type === 'preorder' && ' ORDER'}</span></div><strong className="order-status">{order.status === 'ready' ? 'ORDER READY' : label(order.status)}</strong></div>{order.order_type === 'express' && <p className="order-badge">EXPRESS ORDER</p>}{order.order_type === 'preorder' && <p className="order-badge">PRE-ORDER · Requested {order.requested_date || 'date not set'}</p>}<p className="order-meta">Order date: {new Date(order.created_at).toLocaleDateString()} {order.requested_date && <>· Requested date: {order.requested_date}</>}</p><p>{order.order_items.map((item) => `${item.product_name} × ${item.quantity}`).join(', ')}</p><p className="order-total">Total: ${Number(order.total_amount ?? 0).toFixed(2)}</p>{active && <Progress status={order.status}/>} {order.status === 'ready' && <p className="ready-message">ORDER READY<br/><small>{order.order_number} · {order.order_type} · {order.requested_date || 'No requested date'}</small></p>}<a className="btn btn-outline" href={`/account/orders/${order.id}`}>View order details →</a></article>; }

export function AccountPortal() {
  const client = getSupabaseBrowserClient(); const [profile, setProfile] = useState<Profile | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function load() { if (!client) return; const { data } = await client.auth.getSession(); const user = data.session?.user; if (!user) return; const [{ data: existing }, { data: rows, error: orderError }] = await Promise.all([client.from('customer_profiles').select('*').eq('user_id', user.id).maybeSingle(), client.from('orders').select('id,order_number,order_type,status,total_amount,requested_date,created_at,ready_at,customer_notes,order_items(product_name,quantity,unit_price)').eq('user_id', user.id).order('created_at',{ascending:false})]); if (existing) setProfile(existing); else { const { data: inserted } = await client.from('customer_profiles').upsert({ user_id:user.id, full_name:String(user.user_metadata?.full_name ?? ''), email:user.email ?? '' }).select().single(); if (inserted) setProfile(inserted); } if (orderError) setError(orderError.message); setOrders((rows ?? []) as Order[]); }
  useEffect(() => { load(); }, []);
  async function saveProfile(event: React.FormEvent) { event.preventDefault(); if (!client || !profile) return; setSaving(true); setMessage(''); setError(''); const { data, error: saveError } = await client.from('customer_profiles').update({ full_name:profile.full_name,phone:profile.phone,address:profile.address,city:profile.city,state:profile.state,postal_code:profile.postal_code,updated_at:new Date().toISOString() }).eq('user_id',profile.user_id).select().single(); setSaving(false); if (saveError) setError(saveError.message); else { setProfile(data); setMessage('Save Changes confirmed.'); } }
  if (!profile) return <main className="auth-page"><p>Loading account…</p></main>; const active = orders.filter((o) => !['completed','cancelled'].includes(o.status)); const history = orders.filter((o) => ['completed','cancelled'].includes(o.status));
  return <main className="account-page"><div className="account-summary"><p className="eyebrow">Sassy Salsa customer portal</p><h1>{profile.full_name || 'Your account'}</h1><p>{profile.email} · {profile.phone || 'Phone not added'}</p><p>{[profile.address,profile.city,profile.state,profile.postal_code].filter(Boolean).join(', ') || 'Address not added'}</p><div className="account-counts"><span><strong>{orders.length}</strong>Total orders</span><span><strong>{active.length}</strong>Active orders</span><span><strong>{orders.filter((o)=>o.status==='completed').length}</strong>Completed orders</span></div></div><div className="account-grid"><section className="account-card"><p className="eyebrow">Your details</p><h2>Customer profile</h2><form className="auth-form" onSubmit={saveProfile}><label>Full name<input value={profile.full_name} onChange={(e)=>setProfile({...profile,full_name:e.target.value})}/></label><label>Email<input value={profile.email} disabled/></label><label>Phone<input value={profile.phone??''} onChange={(e)=>setProfile({...profile,phone:e.target.value})}/></label><label>Address<input value={profile.address??''} onChange={(e)=>setProfile({...profile,address:e.target.value})}/></label><div className="form-row"><label>City<input value={profile.city??''} onChange={(e)=>setProfile({...profile,city:e.target.value})}/></label><label>State<input value={profile.state??''} onChange={(e)=>setProfile({...profile,state:e.target.value})}/></label><label>Postal code<input value={profile.postal_code??''} onChange={(e)=>setProfile({...profile,postal_code:e.target.value})}/></label></div><button className="btn btn-primary" disabled={saving}>Save Changes</button></form></section><section className="orders-section"><p className="eyebrow">Fulfillment</p><h2>ACTIVE ORDERS</h2>{active.length ? active.map((o)=><OrderCard order={o} key={o.id}/>) : <p>You don't have any active orders.</p>}<h2>ORDER HISTORY</h2>{history.length ? history.map((o)=><OrderCard order={o} key={o.id}/>) : <p>You don't have any completed orders yet.</p>}{!orders.length && <div className="empty-orders"><p>You don't have any orders yet.</p><a className="btn btn-primary" href="/shop">Shop Salsa</a></div>}</section></div>{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}</main>;
}
