'use client';
import { useEffect, useState } from 'react';
import { getSupabaseBrowserClient } from '@/lib/supabase';
import { Product } from '@/lib/products';

type Profile = { user_id: string; full_name: string; email: string; phone: string | null; address: string | null; city: string | null; state: string | null; postal_code: string | null };
type Order = { id: string; order_number: string; order_type: string; status: string; total_amount: number | null; requested_date: string | null; ready_at: string | null; customer_notes: string | null; order_items: { product_name: string; quantity: number; unit_price: number }[] };

export function AccountPortal() {
  const [profile, setProfile] = useState<Profile | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [products, setProducts] = useState<Product[]>([]); const [userId, setUserId] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [orderType, setOrderType] = useState('normal'); const [productId, setProductId] = useState(''); const [quantity, setQuantity] = useState(1); const [requestedDate, setRequestedDate] = useState(''); const [notes, setNotes] = useState('');
  const client = getSupabaseBrowserClient();
  async function load() { if (!client) return; const { data: sessionData } = await client.auth.getSession(); const user = sessionData.session?.user; if (!user) return; setUserId(user.id); const [{ data: existing }, { data: orderRows, error: orderError }, productResponse] = await Promise.all([client.from('customer_profiles').select('*').eq('user_id', user.id).maybeSingle(), client.from('orders').select('id,order_number,order_type,status,total_amount,requested_date,ready_at,customer_notes,order_items(product_name,quantity,unit_price)').order('created_at',{ascending:false}), fetch('/api/products')]); if (existing) setProfile(existing); else { const created = { user_id: user.id, full_name: String(user.user_metadata?.full_name ?? ''), email: user.email ?? '' }; const { data: inserted } = await client.from('customer_profiles').upsert(created).select().single(); if (inserted) setProfile(inserted); } if (orderError) setError(orderError.message); if (orderRows) setOrders(orderRows as Order[]); const available = await productResponse.json(); if (Array.isArray(available)) { setProducts(available); if (available[0]) setProductId(available[0].id); } }
  useEffect(() => { load(); }, []);
  async function saveProfile(event: React.FormEvent) { event.preventDefault(); if (!client || !profile) return; setSaving(true); setMessage(''); setError(''); const { data, error: saveError } = await client.from('customer_profiles').update({ full_name: profile.full_name, phone: profile.phone, address: profile.address, city: profile.city, state: profile.state, postal_code: profile.postal_code, updated_at: new Date().toISOString() }).eq('user_id', userId).select().single(); setSaving(false); if (saveError) setError(saveError.message); else { setProfile(data); setMessage('Profile saved.'); } }
  async function createOrder(event: React.FormEvent) { event.preventDefault(); if (!client || !productId) return; setSaving(true); setMessage(''); setError(''); const { data, error: createError } = await client.rpc('create_customer_order', { p_order_type: orderType, p_requested_date: requestedDate || null, p_customer_notes: notes || null, p_items: [{ product_id: productId, quantity }] }); setSaving(false); if (createError) setError(createError.message); else { setMessage(`Order ${data} created.`); setNotes(''); setRequestedDate(''); await load(); } }
  if (!profile) return <main className="auth-page"><p>Loading account…</p></main>;
  return <main className="account-page"><div className="account-grid"><section className="account-card"><p className="eyebrow">Your details</p><h1>Your account</h1><form className="auth-form" onSubmit={saveProfile}><label>Full name<input value={profile.full_name} onChange={(e) => setProfile({...profile,full_name:e.target.value})} /></label><label>Email<input value={profile.email} disabled /></label><label>Phone<input value={profile.phone ?? ''} onChange={(e) => setProfile({...profile,phone:e.target.value})} /></label><label>Address<input value={profile.address ?? ''} onChange={(e) => setProfile({...profile,address:e.target.value})} /></label><div className="form-row"><label>City<input value={profile.city ?? ''} onChange={(e) => setProfile({...profile,city:e.target.value})} /></label><label>State<input value={profile.state ?? ''} onChange={(e) => setProfile({...profile,state:e.target.value})} /></label><label>Postal code<input value={profile.postal_code ?? ''} onChange={(e) => setProfile({...profile,postal_code:e.target.value})} /></label></div><button className="btn btn-primary" disabled={saving}>Save profile</button></form></section><section className="account-card"><p className="eyebrow">Order foundation</p><h2>Create a test order</h2><form className="auth-form" onSubmit={createOrder}><label>Order type<select value={orderType} onChange={(e) => setOrderType(e.target.value)}><option value="normal">Normal</option><option value="express">Express</option><option value="preorder">Pre-order</option></select></label><label>Product<select value={productId} onChange={(e) => setProductId(e.target.value)}>{products.map((p) => <option key={p.id} value={p.id}>{p.name} — ${p.price.toFixed(2)}</option>)}</select></label><label>Quantity<input type="number" min="1" value={quantity} onChange={(e) => setQuantity(Math.max(1, Number(e.target.value)))} /></label><label>Requested date<input type="date" value={requestedDate} onChange={(e) => setRequestedDate(e.target.value)} /></label><label>Notes<textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></label><button className="btn btn-primary" disabled={saving || !productId}>Create order</button></form></section></div>{message && <p role="status">{message}</p>}{error && <p role="alert">{error}</p>}<section className="orders-section"><p className="eyebrow">Your orders</p><h2>Order history</h2>{orders.length ? orders.map((order) => <article className="order-card" key={order.id}><div><strong>{order.order_number}</strong><span>{order.order_type}</span><span>{order.status === 'ready' ? 'ORDER READY' : order.status}</span></div><p>{order.order_items.map((item) => `${item.product_name} × ${item.quantity}`).join(', ')}</p><p>Total: ${Number(order.total_amount ?? 0).toFixed(2)}{order.requested_date ? ` · Requested ${order.requested_date}` : ''}{order.ready_at ? ` · Ready ${new Date(order.ready_at).toLocaleDateString()}` : ''}</p></article>) : <p>No orders yet.</p>}</section></main>;
}
