'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { getSupabaseBrowserClient } from '@/lib/supabase';

export function AuthForm({ mode }: { mode: 'sign-in' | 'sign-up' }) {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [fullName, setFullName] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); if (!email.trim() || !/^\S+@\S+\.\S+$/.test(email)) return setError('Enter a valid email address.'); if (password.length < 6) return setError('Password must be at least 6 characters.'); if (mode === 'sign-up' && !fullName.trim()) return setError('Enter your full name.'); const client = getSupabaseBrowserClient(); if (!client) return setError('Authentication is not configured.'); setLoading(true); const result = mode === 'sign-up' ? await client.auth.signUp({ email: email.trim(), password, options: { data: { full_name: fullName.trim() } } }) : await client.auth.signInWithPassword({ email: email.trim(), password }); setLoading(false); if (result.error) return setError(result.error.message); if (mode === 'sign-up' && !result.data.session) return setMessage('Account created. Check your email to confirm your account, then sign in.'); router.push('/account'); router.refresh(); }
  return <form className="auth-form" onSubmit={submit}><h1>{mode === 'sign-up' ? 'Create your account' : 'Welcome back'}</h1>{mode === 'sign-up' && <label>Full name<input value={fullName} onChange={(e) => setFullName(e.target.value)} autoComplete="name" /></label>}<label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete={mode === 'sign-up' ? 'new-password' : 'current-password'} /></label>{error && <p role="alert">{error}</p>}{message && <p role="status">{message}</p>}<button className="btn btn-primary" disabled={loading}>{loading ? 'Please wait…' : mode === 'sign-up' ? 'Create Account' : 'Sign In'}</button><p>{mode === 'sign-up' ? <>Already have an account? <a href="/sign-in">Sign in</a></> : <>New here? <a href="/create-account">Create an account</a></>}</p></form>;
}
