'use client';
import { useEffect, useMemo, useState } from 'react';
import { Product } from '@/lib/products';
import { getSupabaseBrowserClient } from '@/lib/supabase';
import type { CartLine } from './CartDrawer';

type Confirmation = { order_number: string; order_type: string; status: string; total_amount: number; requested_date: string | null; order_items: { product_name: string; quantity: number }[] };
export function CheckoutModal({ open, lines, products, onClose }: { open: boolean; lines: CartLine[]; products: Product[]; onClose: () => void }) {
  const client = getSupabaseBrowserClient(); const [orderType,setOrderType]=useState('normal'); const [profile,setProfile]=useState({full_name:'',email:'',phone:'',address:'',city:'',state:'',postal_code:''}); const [requestedDate,setRequestedDate]=useState(''); const [notes,setNotes]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [confirmation,setConfirmation]=useState<Confirmation|null>(null); const total=useMemo(()=>lines.reduce((sum,line)=>sum+products[line.index].price*line.quantity,0),[lines,products]); const preorderAllowed=lines.length>0&&lines.every((line)=>products[line.index].preorder_enabled); const unavailable=lines.some((line)=>products[line.index].quantity<line.quantity||!products[line.index].is_active);
  useEffect(()=>{if(!open||!client)return; client.auth.getSession().then(async({data})=>{const user=data.session?.user;if(!user)return;const {data:p}=await client.from('customer_profiles').select('*').eq('user_id',user.id).maybeSingle();if(p)setProfile({full_name:p.full_name||'',email:p.email||user.email||'',phone:p.phone||'',address:p.address||'',city:p.city||'',state:p.state||'',postal_code:p.postal_code||''});else setProfile((v)=>({...v,email:user.email||''}));});},[open,client]);
  if(!open)return null;
  async function submit(event:React.FormEvent){event.preventDefault();setError('');if(!client)return setError('Checkout is not configured.');if(!lines.length)return setError('Your cart is empty.');if(unavailable&&orderType!=='preorder')return setError('One or more items no longer has enough inventory.');if(orderType==='preorder'&&!preorderAllowed)return setError('Pre-order is not available for one or more items.');if(orderType==='preorder'&&!requestedDate)return setError('Choose a requested date for a pre-order.');if(!profile.full_name.trim()||!profile.email.trim()||!profile.phone.trim())return setError('Full name, email, and phone are required.');setLoading(true);const {data:session}=await client.auth.getSession();const user=session.session?.user;if(!user){setLoading(false);return setError('Your session expired. Please sign in again.');}const {error:profileError}=await client.from('customer_profiles').upsert({user_id:user.id,...profile,updated_at:new Date().toISOString()});if(profileError){setLoading(false);return setError('We could not save your checkout information.');}const requestId=crypto.randomUUID();const result=await client.rpc('create_customer_order',{p_order_type:orderType,p_requested_date:requestedDate||null,p_customer_notes:notes||null,p_items:lines.map((line)=>({product_id:products[line.index].id,quantity:line.quantity})),p_client_request_id:requestId});if(result.error){setLoading(false);return setError(result.error.message.includes('Insufficient inventory')?'Some items are no longer available in the requested quantity.':result.error.message.includes('preorder')?'Pre-order is not available for one or more items.':'We could not submit your order. Please try again.');}const {data:order}=await client.from('orders').select('order_number,order_type,status,total_amount,requested_date,order_items(product_name,quantity)').eq('id',result.data).single();setConfirmation(order as Confirmation);setLoading(false);}
  if(confirmation)return <div className="checkout-backdrop"><section className="checkout-modal"><button className="checkout-close" onClick={onClose}>×</button><p className="eyebrow">Sassy Salsa</p><h2>ORDER CONFIRMED</h2><p>Order #{confirmation.order_number}</p><p>Status: <strong>{confirmation.status}</strong></p><p>Type: <strong>{confirmation.order_type}</strong></p><ul>{confirmation.order_items.map((item)=><li key={item.product_name}>{item.product_name} × {item.quantity}</li>)}</ul><p>Total: <strong>${Number(confirmation.total_amount).toFixed(2)}</strong></p>{confirmation.requested_date&&<p>Requested date: {confirmation.requested_date}</p>}<p>No payment has been processed.</p><button className="btn btn-primary" onClick={onClose}>Done</button></section></div>;
  return <div className="checkout-backdrop"><section className="checkout-modal"><button className="checkout-close" onClick={onClose}>×</button><p className="eyebrow">Checkout</p><h2>Complete your order</h2><div className="checkout-summary">{lines.map((line)=><p key={products[line.index].id}>{products[line.index].name} × {line.quantity} <strong>${(products[line.index].price*line.quantity).toFixed(2)}</strong></p>)}<p><strong>Total ${total.toFixed(2)}</strong></p></div><form className="auth-form" onSubmit={submit}><label>Order type<select value={orderType} onChange={(e)=>setOrderType(e.target.value)}><option value="normal">Normal order — standard fulfillment</option><option value="express">Express order — expedited request</option>{preorderAllowed&&<option value="preorder">Pre-order — request for a future date</option>}</select></label><label>Full name<input value={profile.full_name} onChange={(e)=>setProfile({...profile,full_name:e.target.value})}/></label><label>Email<input type="email" value={profile.email} onChange={(e)=>setProfile({...profile,email:e.target.value})}/></label><label>Phone<input value={profile.phone} onChange={(e)=>setProfile({...profile,phone:e.target.value})}/></label><label>Address<input value={profile.address} onChange={(e)=>setProfile({...profile,address:e.target.value})}/></label><div className="form-row"><label>City<input value={profile.city} onChange={(e)=>setProfile({...profile,city:e.target.value})}/></label><label>State<input value={profile.state} onChange={(e)=>setProfile({...profile,state:e.target.value})}/></label><label>Postal code<input value={profile.postal_code} onChange={(e)=>setProfile({...profile,postal_code:e.target.value})}/></label></div>{orderType==='preorder'&&<label>Requested date<input type="date" value={requestedDate} onChange={(e)=>setRequestedDate(e.target.value)}/></label>}<label>Customer notes<textarea value={notes} onChange={(e)=>setNotes(e.target.value)}/></label>{unavailable&&orderType!=='preorder'&&<p role="alert">Inventory changed. Please review your cart.</p>}{error&&<p role="alert">{error}</p>}<button className="btn btn-primary" disabled={loading||unavailable&&orderType!=='preorder'}>{loading?'Submitting…':'Submit order'}</button></form></section></div>;
}
